dist: focal
language: cpp

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - ${TRAVIS_BUILD_DIR}/clang
    - ${TRAVIS_BUILD_DIR}/clang-windows
    - ${TRAVIS_BUILD_DIR}/llvm-utils
    - ${TRAVIS_BUILD_DIR}/upload-tool
    - $HOME/AppData/Local/Temp/chocolatey

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -q update
        - sudo apt-get install make gcc-11 g++-11 cmake
      addons:
        apt:
          update: true
      env:
      - MATRIX_EVAL="CC=gcc-11 && CXX=g++-11"

    - os: linux
      compiler: clang
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - wget 'https://apt.llvm.org/llvm-snapshot.gpg.key' -O /tmp/key.gpg | cat /tmp/key.gpg | sudo apt-key add -
        - sudo apt-get -q update
        - sudo apt-get install make cmake
        - sudo apt-get install clang-14 clang-tools-14 clang-format-14 cppcheck libclang-cpp14 libc++-14-dev libc++abi-14-dev lcov
        - eval "${MATRIX_EVAL}"
      addons:
        apt:
          update: true
      env:
        - MATRIX_EVAL="CC=clang-14 && CXX=clang++-14"

before_install:
    - eval "${MATRIX_EVAL}" 

script: VERBOSE=1 make && ctest -V
addons:
  apt:
    packages: lcov

#after_success:
# Create lcov report
#- lcov --capture --directory . --output-file coverage.info
#- lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
#- lcov --list coverage.info # debug info
# Uploading report to CodeCov
# - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
