dist: focal
language: cpp

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - ${TRAVIS_BUILD_DIR}/clang
    - ${TRAVIS_BUILD_DIR}/clang-windows
    - ${TRAVIS_BUILD_DIR}/llvm-utils
    - ${TRAVIS_BUILD_DIR}/upload-tool
    - $HOME/AppData/Local/Temp/chocolatey

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -q update
        - sudo apt-get install make gcc-11 g++-11 cmake
      addons:
        apt:
          update: true
      env:
      - MATRIX_EVAL="CC=gcc-11 && CXX=g++-11"

before_install:
    - eval "${MATRIX_EVAL}" 

script: VERBOSE=1 make && ctest -V
addons:
  apt:
    packages: lcov

#after_success:
# Create lcov report
#- lcov --capture --directory . --output-file coverage.info
#- lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
#- lcov --list coverage.info # debug info
# Uploading report to CodeCov
# - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
